version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crc-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wp8dyy56ht7o"
s3_prefix = "crc-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
